#######################################################
# Spring Profiles Configuration
#######################################################

# Active profile for development
 spring.profiles.active=prod

# Active profile for production
# Uncomment the following line for the production environment
# spring.profiles.active=prod

#######################################################
# End of Configuration
#######################################################

