spring.datasource.url=jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}?sslmode=require
spring.datasource.username=${PROD_DB_USER}
spring.datasource.password=${PROD_DB_PASSWORD}

# Postgres setup
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQL95Dialect
spring.jpa.hibernate.ddl-auto= update


# App Properties
hagz.app.jwtSecret= ${JWT_SECRET}
hagz.app.jwtExpirationMs= 86400000

# Log
log4j.logger.org.hibernate=DEBUG
log4j.logger.org.hibernate.SQL=DEBUG