spring.datasource.url=jdbc:${PROD_DB_URL}
spring.datasource.username=${PROD_DB_USER}
spring.datasource.password=${PROD_DB_PASSWORD}

# MySql setup
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgresSQLDialect
spring.jpa.hibernate.ddl-auto= update


# App Properties
hagz.app.jwtSecret= ${JWT_SECRET}
hagz.app.jwtExpirationMs= 86400000

# Log
log4j.logger.org.hibernate=DEBUG
log4j.logger.org.hibernate.SQL=DEBUG